### ISSUE TITLE
Ignoring null values when encoding...

### ISSUE THREAD

**Issue by bjarne-hansen** [jolleekin/jsonx#12]
Is there a way to "ignore" null values when encoding?
Can't seem to find this, but it could be an option like the indent option.

//bjarne

**Comment by jolleekin** [comment]
Can you give me some reasons/use cases why this is necessary?

**Comment by bjarne-hansen** [comment]
Well ... not besides that null tends to be the same as "not there at all" ...

{
  somefield: 15,
  someother: "hello",
  somenot: null
}

{
  somefield: 15,
  someother: "hello",
}

Just thinks that the latter looks better and is more compact. On the client/server some default would typically apply ...

... but just a suggestion ... not an "issue" as such.

**Comment by stevenroose** [comment]
I came across this project looking for just this feature. An `@jsonIgnoreNull` annotation would be awesome!

**Comment by stevenroose** [comment]
I implemented this annotation. Until @jolleekin merges it, feel free to use my master branch (as I will).

**Comment by jolleekin** [comment]
An annotation is a quick solution to this problem. However, it will not work with third-party classes (classes you do not own). Ultimately, adding a parameter to the constructors of `JsonxCodec` and `JsonxEncoder` will be the best solution.

Supporting both may be another option.

**Comment by jolleekin** [comment]
I think the package really needs redesigning. Right now, most settings are top level (`jsonToObjects`, `objectToJsons`, `propertyNameDecoder`, and `propertyNameEncoder`), preventing the package from being used with different APIs written in different languages in the same application. For example, you cannot use the package to talk to an API in C# (which uses PascalCase or camelCase naming convention) and an API in ruby (which uses underscore_case naming convention).

However, I will avoid major changes until Dart 2.0 is out. In the meantime, I'll merge your request to add @jsonIgnoreNull.

**Comment by stevenroose** [comment]
Yeah it should actually convert camel casing to underscores. Polymer does
(or used to do) the same with dashes for html attributes.

I agree that there are some interesting potential features for a 1.0
release!
